# MSE, ml-motofelica@nttd-mse.com
# 04/27/2012 First Release of FeliCa device driver
# 06/05/2012 Modification for the file path of FeliCa device driver
#
# Makefile for FeliCa device driver.
#
ifeq ($(CONFIG_FELICA_HW),y)
obj-m	+= felica.o
obj-m	+= felica_uart.o
obj-m	+= felica_rws.o
endif

